Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Models/Bridge.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SE406_Payne.Models
{
    public class Bridge
    {
        [Required(ErrorMessage = "Bridge ID is required")]
        public Guid Bridgeid { get; set; }

        [Required(ErrorMessage = "Material Design ID is required")]
        public Guid MaterialDesignId { get; set; }

        [Required(ErrorMessage = "Construction Design ID is required")]
        public Guid ConstructionDesignId { get; set; }

        [Required(ErrorMessage = "Functional Class ID is required")]
        public Guid FunctionalClassId { get; set; }

        [Required(ErrorMessage = "Status ID is required")]
        public Guid StatusId { get; set; }

        [Required(ErrorMessage = "County ID  is required")]
        public Guid CountyId { get; set; }

        [Required(ErrorMessage = "Nbi Number is a required field")]
        [MinLength(5, ErrorMessage = "Minimum length of Nbi is 5 characters")]
        [MaxLength(100, ErrorMessage = "Max length of Nbi is 100 characters")]
        public string NbiNumber { get; set; }

        public decimal? Rating { get; set; }
        public string RouteNumber { get; set; }

        [Required(ErrorMessage = "City is required")]
        [MinLength(5, ErrorMessage = "Minimum length is 5 characters")]
        [MaxLength(50, ErrorMessage = "Max length is 50 characters")]
        public string City { get; set; }

        [Required(ErrorMessage = "Intersecting Feature is a required field")]
        [MinLength(5, ErrorMessage = "Minimum length is 5 characters")]
        [MaxLength(255, ErrorMessage = "Max length is 255 characters")]
        public string IntersectingFeature { get; set; }

        [Required(ErrorMessage = "Carried Feature is a required field")]
        [MinLength(5, ErrorMessage = "Minimum length is 5 characters")]
        [MaxLength(255, ErrorMessage = "Max length of is 255 characters")]
        public string CarriedFeature { get; set; }

        [Required(ErrorMessage = "Location is required")]
        [MinLength(5, ErrorMessage = "Minimum length is 5 characters")]
        [MaxLength(255, ErrorMessage = "Max length of is 255 characters")]
        public string Location { get; set; }

        [Required(ErrorMessage = "Built is required")]
        [Range(1600, 2025, ErrorMessage = "Year out of range")]
        public int Built { get; set; }

        [Range(1600, 2025, ErrorMessage = "Year out of range")]
        public int? Reconstructed { get; set; }

        [Required(ErrorMessage = "Total Length is a required field")]
        public decimal TotalLength { get; set; }

        
    }
}

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Models/BridgeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SE406_Payne.Models
{
    public class BridgeViewModel
    {
        public List<Bridge> BridgeList { get; set; }
        public Bridge NewBridge { get; set; }
        public List<SelectListItem> MaterialDesigns { get; set; }
        public List<SelectListItem> ConstructionDesigns { get; set; }
        public List<SelectListItem> FunctionalClasses { get; set; }
        public List<SelectListItem> StatusCodes { get; set; }
        public List<SelectListItem> Counties { get; set; }
    }
}

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Controllers/BridgeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SE406_Payne.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SE406_Payne.Controllers
{
    public class BridgeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            BridgeViewModel bridgeVM = new BridgeViewModel();
            using (var db = new BridgeDBContext())
            {
                bridgeVM.BridgeList = db.Bridges.ToList();
                bridgeVM.NewBridge = new Bridge();
                bridgeVM.MaterialDesigns = GetMaterialDesignsDDL();
                bridgeVM.ConstructionDesigns = GetConstructionDesignsDDL();
                bridgeVM.FunctionalClasses = GetFunctionalClassesDDL();
                bridgeVM.StatusCodes = GetStatusCodesDDL();
                bridgeVM.Counties = GetCountiesDDL();
            }

                return View(bridgeVM);
        }

        //insert new bridges
        [HttpPost]
        public IActionResult Index(BridgeViewModel bridgeVM)
        {
            if (ModelState.IsValid) 
            {
                using (var db = new BridgeDBContext())
                {
                    db.Bridges.Add(bridgeVM.NewBridge);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        //GET Fill Form
        public IActionResult Edit(Guid id)
        {
            //create an instance of the view model
            BridgeViewModel bridgeVM = new BridgeViewModel();
            using (BridgeDBContext db = new BridgeDBContext())
            {
                //find id passed in location in the database
                bridgeVM.NewBridge = db.Bridges.Where(
                    e => e.Bridgeid == id).SingleOrDefault();
                //fill Material Designs drop down
                bridgeVM.MaterialDesigns = GetMaterialDesignsDDL();
                //fill Construction Designs drop down
                bridgeVM.ConstructionDesigns = GetConstructionDesignsDDL();
                //fill Functional Classes drop down
                bridgeVM.FunctionalClasses = GetFunctionalClassesDDL();
                //fill Status Codes drop down
                bridgeVM.StatusCodes = GetStatusCodesDDL();
                //fill Counties drop down
                bridgeVM.Counties = GetCountiesDDL();

                //return the view model
                return View(bridgeVM);
            }
        }

        //POST for edit action
        [HttpPost]
        public IActionResult Edit(BridgeViewModel obj)
        {
            //check for valid model state
            if(ModelState.IsValid)
            {
                using (BridgeDBContext db = new BridgeDBContext())
                {
                    //instance of object
                    Bridge b = obj.NewBridge;
                    //retrieve info from route data
                    b.Bridgeid = Guid.Parse(RouteData.Values["id"].ToString());
                    //update record state
                    db.Entry(b).State = EntityState.Modified;
                    //save changes
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        private static List<SelectListItem>GetMaterialDesignsDDL()
        {
            List<SelectListItem> material = new List<SelectListItem>();
            MaterialDesignViewModel mdvm = new MaterialDesignViewModel();
            using (var db = new MaterialDesignDBContext())
            {
                mdvm.MaterialDesignList = db.MaterialDesigns.ToList();
            }
            foreach(MaterialDesign m in mdvm.MaterialDesignList)
            {
                material.Add(new SelectListItem
                {
                    Text = m.MaterialDesignType,
                    Value = m.MaterialDesignId.ToString()
                });
            }
            return material;
        }

        private static List<SelectListItem>GetConstructionDesignsDDL()
        {
            List<SelectListItem> cDesign = new List<SelectListItem>();
            ConstructionDesignViewModel cdvm = new ConstructionDesignViewModel();
            using (var db = new ConstructionDesignDBContext())
            {
                cdvm.ConstructionDesignList = db.ConstructionDesigns.ToList();
            }
            foreach(ConstructionDesign c in cdvm.ConstructionDesignList)
            {
                cDesign.Add(new SelectListItem
                {
                    Text = c.ConstructionDesignType,
                    Value = c.ConstructionDesignId.ToString()
                });
            }
            return cDesign;
        }

        private static List<SelectListItem>GetFunctionalClassesDDL()
        {
            List<SelectListItem> fClass = new List<SelectListItem>();
            FunctionalClassViewModel fcvm = new FunctionalClassViewModel();
            using (var db = new FunctionalClassDBContext())
            {
                fcvm.FunctionalClassList = db.FunctionalClasses.ToList();
            }
            foreach(FunctionalClass f in fcvm.FunctionalClassList)
            {
                fClass.Add(new SelectListItem
                {
                    Text = f.FunctionalClassType,
                    Value = f.FunctionalClassId.ToString()
                });
            }
            return fClass;
        }

        private static List<SelectListItem> GetStatusCodesDDL()
        {
            List<SelectListItem> sCode = new List<SelectListItem>();
            StatusCodeViewModel scvm = new StatusCodeViewModel();
            using (var db = new StatusCodeDBContext())
            {
                scvm.StatusCodeList = db.StatusCodes.ToList();
            }
            foreach(StatusCode s in scvm.StatusCodeList)
            {
                sCode.Add(new SelectListItem
                {
                    Text = s.StatusName,
                    Value = s.StatusCodeId.ToString()
                });
            }
            return sCode;
        }

        private static List<SelectListItem> GetCountiesDDL()
        {
            List<SelectListItem> counties = new List<SelectListItem>();
            CountyViewModel cvm = new CountyViewModel();
            using (var db = new CountyDBContext())
            {
                cvm.CountyList = db.Counties.ToList();
            }
            foreach(County c in cvm.CountyList)
            {
                counties.Add(new SelectListItem
                {
                    Text = c.CountyName,
                    Value = c.CountyId.ToString()
                });
            }
            return counties;
        }
    }
}

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Views/Bridge/Edit.cshtml
@model SE406_Payne.Models.BridgeViewModel
@section list {
    <h1>Bridges</h1>
}
<div class="container-fluid">
    @using (Html.BeginForm("Edit", "Bridge", FormMethod.Post))
    {
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.Bridgeid)
                    @Html.TextBoxFor(Model => Model.NewBridge.Bridgeid,
              new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.Bridgeid"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.MaterialDesignId)
                    <select asp-for="@Model.NewBridge.MaterialDesignId"
                            asp-items="@Model.MaterialDesigns" class="form-control">
                        <option value="" selected>Choose Material Design ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.MaterialDesignId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.ConstructionDesignId)
                    <select asp-for="@Model.NewBridge.ConstructionDesignId"
                            asp-items="@Model.ConstructionDesigns" class="form-control">
                        <option value="" selected>Choose Construction Design ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.ConstructionDesignId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.FunctionalClassId)
                    <select asp-for="@Model.NewBridge.FunctionalClassId"
                            asp-items="@Model.FunctionalClasses" class="form-control">
                        <option value="" selected>Choose Functional Class ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.FunctionalClassId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.StatusId)
                    <select asp-for="@Model.NewBridge.StatusId"
                            asp-items="@Model.StatusCodes" class="form-control">
                        <option value="" selected>Choose Status Code ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.StatusId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.CountyId)
                    <select asp-for="@Model.NewBridge.CountyId"
                            asp-items="@Model.Counties" class="form-control">
                        <option value="" selected>Choose County ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.CountyId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.NbiNumber)
                    @Html.TextBoxFor(Model => Model.NewBridge.NbiNumber,
              new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.NbiNumber"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.Rating)
                    @Html.TextBoxFor(Model => Model.NewBridge.Rating,
              new { @class = "form-control" })
                </div>
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.RouteNumber)
                    @Html.TextBoxFor(Model => Model.NewBridge.RouteNumber,
             new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.City)
                    @Html.TextBoxFor(Model => Model.NewBridge.City,
             new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.City"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.IntersectingFeature)
                    @Html.TextBoxFor(Model => Model.NewBridge.IntersectingFeature,
             new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.IntersectingFeature"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.CarriedFeature)
                    @Html.TextBoxFor(Model => Model.NewBridge.CarriedFeature,
             new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.CarriedFeature"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.Location)
                    @Html.TextBoxFor(Model => Model.NewBridge.Location,
             new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.Location"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.Built)
                    @Html.TextBoxFor(Model => Model.NewBridge.Built,
             new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.Built"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.Reconstructed)
                    @Html.TextBoxFor(Model => Model.NewBridge.Reconstructed,
             new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.TotalLength)
                    @Html.TextBoxFor(Model => Model.NewBridge.TotalLength,
             new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.TotalLength"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-lg" />
                    <div class="btn btn-lg">
                        @Html.ActionLink("Back to Bridges", "Index")
                    </div>
                </div>
            </div>
            <div class="col-sm-3"></div>
        </div>
    }
</div>

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Views/Bridge/Index.cshtml
@model SE406_Payne.Models.BridgeViewModel
@section list {
    <h1>Bridges</h1>
}
<div class="container-fluid">
    @using (Html.BeginForm("Index", "Bridge", FormMethod.Post))
    {
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.Bridgeid)
                    @Html.TextBoxFor(Model => Model.NewBridge.Bridgeid,
                     new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.Bridgeid"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.MaterialDesignId)
                    <select asp-for="@Model.NewBridge.MaterialDesignId"
                            asp-items="@Model.MaterialDesigns" class="form-control">
                        <option value="" selected>Choose Material Design ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.MaterialDesignId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.ConstructionDesignId)
                    <select asp-for="@Model.NewBridge.ConstructionDesignId"
                            asp-items="@Model.ConstructionDesigns" class="form-control">
                        <option value="" selected>Choose Construction Design ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.ConstructionDesignId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.FunctionalClassId)
                    <select asp-for="@Model.NewBridge.FunctionalClassId"
                            asp-items="@Model.FunctionalClasses" class="form-control">
                        <option value="" selected>Choose Functional Class ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.FunctionalClassId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.StatusId)
                    <select asp-for="@Model.NewBridge.StatusId"
                            asp-items="@Model.StatusCodes" class="form-control">
                        <option value="" selected>Choose Status Code ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.StatusId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.CountyId)
                    <select asp-for="@Model.NewBridge.CountyId"
                            asp-items="@Model.Counties" class="form-control">
                        <option value="" selected>Choose County ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewBridge.CountyId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.NbiNumber)
                    @Html.TextBoxFor(Model => Model.NewBridge.NbiNumber,
                     new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewBridge.NbiNumber"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewBridge.Rating)
                    @Html.TextBoxFor(Model => Model.NewBridge.Rating,
                     new { @class = "form-control" })
                </div>
            </div>
        <div class="col-sm-1"></div>
        <div class="col-sm-4">
            <div class="form-group">
                @Html.LabelFor(Model => Model.NewBridge.RouteNumber)
                @Html.TextBoxFor(Model => Model.NewBridge.RouteNumber,
                    new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.NewBridge.City)
                @Html.TextBoxFor(Model => Model.NewBridge.City,
                    new { @class = "form-control" })
                <span asp-validation-for="@Model.NewBridge.City"
                      class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.NewBridge.IntersectingFeature)
                @Html.TextBoxFor(Model => Model.NewBridge.IntersectingFeature,
                    new { @class = "form-control" })
                <span asp-validation-for="@Model.NewBridge.IntersectingFeature"
                      class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.NewBridge.CarriedFeature)
                @Html.TextBoxFor(Model => Model.NewBridge.CarriedFeature,
                    new { @class = "form-control" })
                <span asp-validation-for="@Model.NewBridge.CarriedFeature"
                      class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.NewBridge.Location)
                @Html.TextBoxFor(Model => Model.NewBridge.Location,
                    new { @class = "form-control" })
                <span asp-validation-for="@Model.NewBridge.Location"
                      class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.NewBridge.Built)
                @Html.TextBoxFor(Model => Model.NewBridge.Built,
                    new { @class = "form-control" })
                <span asp-validation-for="@Model.NewBridge.Built"
                      class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.NewBridge.Reconstructed)
                @Html.TextBoxFor(Model => Model.NewBridge.Reconstructed,
                    new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.NewBridge.TotalLength)
                @Html.TextBoxFor(Model => Model.NewBridge.TotalLength,
                    new { @class = "form-control" })
                <span asp-validation-for="@Model.NewBridge.TotalLength"
                      class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-lg" />
            </div>
        </div>
            <div class="col-sm-3"></div>
      </div>
       
    }
    <div class="row">
        <div class="col-sm-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>City</th>
                        <th>Rating</th>
                        <th>Route Number</th>
                        <th>Intersecting Feature</th>
                        <th>Carried Feature</th>
                        <th>Location</th>
                        <th> </th>
                    </tr>
                    @foreach (var bridge in Model.BridgeList)
                    {
                        <tr>
                            <td>@bridge.City</td>
                            <td>@bridge.Rating</td>
                            <td>@bridge.RouteNumber</td>
                            <td>@bridge.IntersectingFeature</td>
                            <td>@bridge.CarriedFeature</td>
                            <td>@bridge.Location</td>
                            <td><a asp-action="Edit" asp-route-id="@bridge.Bridgeid">Edit</a></td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>