Lab_4/SE406_Payne_Lab4/SE406_Payne/src/SE406_Payne/Models/InspectionCode.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SE406_Payne.Models
{
    public class InspectionCode
    {
        public Guid InspectionCodeId { get; set; }
        public string InspectionCodeName { get; set; }
        public string InspectionCodeDesc { get; set; }
    }
}

Lab_4/SE406_Payne_Lab4/SE406_Payne/src/SE406_Payne/Models/InspectionCodeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SE406_Payne.Models
{
    public class InspectionCodeViewModel
    {
        public List<InspectionCode> InspectionCodeList { get; set; }
        public InspectionCode NewInspectionCode { get; set; }
    }
}

Lab_4/SE406_Payne_Lab4/SE406_Payne/src/SE406_Payne/Controllers/InspectionCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SE406_Payne.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SE406_Payne.Controllers
{
    public class InspectionCodeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            InspectionCodeViewModel inspectionCodeVM = new InspectionCodeViewModel();
            using (var db = new InspectionCodesDBContext())
            {
                inspectionCodeVM.InspectionCodeList = db.InspectionCodes.ToList();
                inspectionCodeVM.NewInspectionCode = new InspectionCode();
            }

            return View(inspectionCodeVM);
        }

        [HttpPost]
        public IActionResult Index(InspectionCodeViewModel inspectionCodeVM)
        {
            using (var db = new InspectionCodesDBContext())
            {
                db.InspectionCodes.Add(inspectionCodeVM.NewInspectionCode);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
        }

    }
}

Lab_4/SE406_Payne_Lab4/SE406_Payne/src/SE406_Payne/Views/InspectionCode/Index.cshtml
@model SE406_Payne.Models.InspectionCodeViewModel

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            @using (Html.BeginForm("Index", "InspectionCode", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewInspectionCode.InspectionCodeId)
                    @Html.TextBoxFor(Model => Model.NewInspectionCode.InspectionCodeId,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewInspectionCode.InspectionCodeName)
                    @Html.TextBoxFor(Model => Model.NewInspectionCode.InspectionCodeName,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewInspectionCode.InspectionCodeDesc)
                    @Html.TextBoxFor(Model => Model.NewInspectionCode.InspectionCodeDesc,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-lg" />
                </div>
            }
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <h2>Inspection Codes</h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>Inspection Code ID</th>
                        <th>Inspection Code Name</th>
                        <th>Inspection Code Desc</th>
                    </tr>
                    @foreach (var InspectionCode in Model.InspectionCodeList)
                    {
                        <tr>
                            <td>@InspectionCode.InspectionCodeId</td>
                            <td>@InspectionCode.InspectionCodeName</td>
                            <td>@InspectionCode.InspectionCodeDesc</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>


</div>