Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Models/MaintenanceRecord.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SE406_Payne.Models
{
    public class MaintenanceRecord
    {
        [Required(ErrorMessage = "Maintenance Record ID is required")]
        public Guid MaintenanceRecordId { get; set; }

        [Required(ErrorMessage = "Maintenance Action ID is required")]
        public Guid MaintenanceActionId { get; set; }

        [Required(ErrorMessage = "Inspector ID is required")]
        public Guid InspectorId { get; set; }

        [Required(ErrorMessage = "Maintenance Projected Start is required")]
        public DateTime MaintenanceProjectedStart { get; set; }

        [Required(ErrorMessage = "Maintenance Projected End is required")]
        public DateTime MaintenanceProjectedEnd { get; set; }

        public DateTime? MaintenanceActualStart { get; set; }
        public DateTime? MaintenanceActualEnd { get; set; }

        [Required(ErrorMessage = "Maintenance Projected Cost is required")]
        public decimal MaintenanceProjectedCost { get; set; }

        public decimal? MaintenanceActualCost { get; set; }
        public string MaintenanceNotes { get; set; }
        public string InspectorNotes { get; set; }
    }
}

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Models/MaintenanceRecordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SE406_Payne.Models
{
    public class MaintenanceRecordViewModel
    {
        public List<MaintenanceRecord> MaintenanceRecordList { get; set; }
        public MaintenanceRecord NewMaintenanceRecord { get; set; }
        public List<SelectListItem>Inspectors { get; set; }
        public List<SelectListItem> MaintenanceActions { get; set; }

    }
}

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Controllers/MaintenanceRecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SE406_Payne.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SE406_Payne.Controllers
{
    public class MaintenanceRecordController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            MaintenanceRecordViewModel maintenanceRecordVM = new MaintenanceRecordViewModel();
            using (var db = new MaintenanceRecordDBContext())
            {
                maintenanceRecordVM.MaintenanceRecordList = db.MaintenanceRecords.ToList();
                maintenanceRecordVM.NewMaintenanceRecord = new MaintenanceRecord();
                maintenanceRecordVM.Inspectors = GetInspectorsDDL();
                maintenanceRecordVM.MaintenanceActions = GetMaintenanceActionsDDL();
            }

            return View(maintenanceRecordVM);
        }

        //insert new maintenance records
        [HttpPost]
        public IActionResult Index(MaintenanceRecordViewModel maintenanceRecordAdd)
        {
            if (ModelState.IsValid)
            {
                using (var db = new MaintenanceRecordDBContext())
                {
                    db.MaintenanceRecords.Add(maintenanceRecordAdd.NewMaintenanceRecord);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        //GET Filled in Form
        public IActionResult Edit(Guid id)
        {
            //a new instance of the view model
            MaintenanceRecordViewModel mRecordVM = new MaintenanceRecordViewModel();
            using (MaintenanceRecordDBContext db = new MaintenanceRecordDBContext())
            {
                //find id location in database
                mRecordVM.NewMaintenanceRecord = db.MaintenanceRecords.Where(
                    e => e.MaintenanceRecordId == id).SingleOrDefault();
                //fill in inspector drop down
                mRecordVM.Inspectors = GetInspectorsDDL();
                //fill in maintenance actions drop down
                mRecordVM.MaintenanceActions = GetMaintenanceActionsDDL();

                //return view model
                return View(mRecordVM);
            }
        }

        //POST define edit action
        [HttpPost]
        public IActionResult Edit(MaintenanceRecordViewModel obj)
        {
            //check for valid view model
            if(ModelState.IsValid)
            {
                using (MaintenanceRecordDBContext db = new MaintenanceRecordDBContext())
                {
                    //object for view model
                    MaintenanceRecord mr = obj.NewMaintenanceRecord;
                    //retrieve primary key/id from route data
                    mr.MaintenanceRecordId = Guid.Parse(RouteData.Values["id"].ToString());
                    //update record status
                    db.Entry(mr).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        private static List<SelectListItem> GetInspectorsDDL()
        {
            List<SelectListItem> inspect = new List<SelectListItem>();
            InspectorViewModel ivm = new InspectorViewModel();
            using (var db = new InspectorDBContext())
            {
                ivm.InspectorList = db.Inspectors.ToList();
            }
            foreach (Inspector i in ivm.InspectorList)
            {
                inspect.Add(new SelectListItem
                    {
                        Text = i.InspectorFirst + " " + i.InspectorLast,
                        Value = i.InspectorId.ToString()
                });
            }
            return inspect;
        }

        private static List<SelectListItem> GetMaintenanceActionsDDL()
        {
            List<SelectListItem> action = new List<SelectListItem>();
            MaintenanceActionViewModel mavm = new MaintenanceActionViewModel();
            using (var db = new MaintenanceActionDBContext())
            {
                mavm.MaintenanceActionList = db.MaintenanceActions.ToList();
            }
            foreach (MaintenanceAction ma in mavm.MaintenanceActionList)
            {
                action.Add(new SelectListItem
                {
                    Text = ma.MaintenanceActionName,
                    Value = ma.MaintenanceActionId.ToString()
                });
            }
            return action;
        }

    }
}

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Views/MaintenanceRecord/Edit.cshtml
@model SE406_Payne.Models.MaintenanceRecordViewModel
@section list {
    <h1>Maintenance Records</h1>
}
<div class="container-fluid">

    @using (Html.BeginForm("Edit", "MaintenanceRecord", FormMethod.Post))
            {
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceRecordId)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceRecordId,
                    new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceRecordId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceActionId)
                    <select asp-for="@Model.NewMaintenanceRecord.MaintenanceActionId"
                            asp-items="@Model.MaintenanceActions" class="form-control">
                        <option value="" selected>Choose Maintenance Action Id</option>
                    </select>
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceActionId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.InspectorId)
                    <select asp-for="@Model.NewMaintenanceRecord.InspectorId"
                            asp-items="@Model.Inspectors" class="form-control">
                        <option value="" selected>Choose Inspector ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewMaintenanceRecord.InspectorId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedStart)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedStart,
                    new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceProjectedStart"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedEnd)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedEnd,
                    new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceProjectedEnd"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceActualStart)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceActualStart,
                    new { @class = "form-control" })
                </div>
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceActualEnd)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceActualEnd,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedCost)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedCost,
                   new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceProjectedCost"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceActualCost)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceActualCost,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceNotes)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceNotes,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.InspectorNotes)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.InspectorNotes,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-lg" />
                    <div class="btn btn-lg">
                        @Html.ActionLink("Back to Maintenance Records", "Index")
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="col-sm-3"></div>
</div>

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Views/MaintenanceRecord/Index.cshtml
@model SE406_Payne.Models.MaintenanceRecordViewModel
@section list {
    <h1>Maintenance Records</h1>
}
<div class="container-fluid">

    @using (Html.BeginForm("Index", "MaintenanceRecord", FormMethod.Post))
            {
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceRecordId)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceRecordId,
                    new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceRecordId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceActionId)
                    <select asp-for="@Model.NewMaintenanceRecord.MaintenanceActionId"
                            asp-items="@Model.MaintenanceActions" class="form-control">
                        <option value="" selected>Choose Maintenance Action Id</option>
                    </select>
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceActionId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.InspectorId)
                    <select asp-for="@Model.NewMaintenanceRecord.InspectorId"
                            asp-items="@Model.Inspectors" class="form-control">
                        <option value="" selected>Choose Inspector ID</option>
                    </select>
                    <span asp-validation-for="@Model.NewMaintenanceRecord.InspectorId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedStart)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedStart,
                    new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceProjectedStart"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedEnd)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedEnd,
                    new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceProjectedEnd"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceActualStart)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceActualStart,
                    new { @class = "form-control" })
                </div>
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm-4">

                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceActualEnd)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceActualEnd,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedCost)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceProjectedCost,
                   new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceRecord.MaintenanceProjectedCost"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceActualCost)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceActualCost,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.MaintenanceNotes)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.MaintenanceNotes,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceRecord.InspectorNotes)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceRecord.InspectorNotes,
                   new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-lg" />
                </div>
            </div>
        </div>
    }

    <div class="col-sm-3"></div>
    <div class="row">
        <div class="col-sm-12">
            <h2>Maintenance Records</h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>Maint ID</th>
                        <th>Maint Action ID</th>
                        <th>Maint Proj End</th>
                        <th>Maint Actual Start</th>
                        <th>Maint Actual End</th>
                        <th>Maint Actual Cost</th>
                        <th> </th>
                    </tr>
                    @foreach (var MaintenanceRecord in Model.MaintenanceRecordList)
                    {
                        <tr>
                            <td>@MaintenanceRecord.MaintenanceRecordId</td>
                            <td>
                                @if (MaintenanceRecord.MaintenanceActionId != null)
                                {
                                    @Model.MaintenanceActions.Where(ma => ma.Value == MaintenanceRecord.MaintenanceActionId.ToString()).FirstOrDefault().Text;

                                }
                            </td>
                            <td>@MaintenanceRecord.MaintenanceProjectedEnd</td>
                            <td>@MaintenanceRecord.MaintenanceActualStart</td>
                            <td>@MaintenanceRecord.MaintenanceActualEnd</td>
                            <td>@MaintenanceRecord.MaintenanceActualCost</td>
                            <td><a asp-action="Edit" asp-route-id="@MaintenanceRecord.MaintenanceRecordId">Edit</a></td>
                        </tr>

                    }
                </table>
            </div>
        </div>
    </div>


</div>