Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Models/MaintenanceActionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SE406_Payne.Models
{
    public class MaintenanceActionViewModel
    {
        public List<MaintenanceAction> MaintenanceActionList { get; set; }
        public MaintenanceAction NewMaintenanceAction { get; set; }
    }
}

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Controllers/MaintenanceActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SE406_Payne.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SE406_Payne.Controllers
{
    public class MaintenanceActionController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            MaintenanceActionViewModel maintenanceActionVM = new MaintenanceActionViewModel();
            using (var db = new MaintenanceActionDBContext())
            {
                maintenanceActionVM.MaintenanceActionList = db.MaintenanceActions.ToList();
                maintenanceActionVM.NewMaintenanceAction = new MaintenanceAction();
            }

            return View(maintenanceActionVM);
        }

        //insert new maintenance actions
        [HttpPost]
        public IActionResult Index(MaintenanceActionViewModel maintenanceActionAdd)
        {
            if (ModelState.IsValid)
            {
                using (var db = new MaintenanceActionDBContext())
                {
                    db.MaintenanceActions.Add(maintenanceActionAdd.NewMaintenanceAction);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        //GET Filled in Form
        public IActionResult Edit(Guid id)
        {
            //a new instance of the view model
            MaintenanceActionViewModel mActionVM = new MaintenanceActionViewModel();
            using (MaintenanceActionDBContext db = new MaintenanceActionDBContext())
            {
                //find id location in databased
                mActionVM.NewMaintenanceAction = db.MaintenanceActions.Where(
                    e => e.MaintenanceActionId == id).SingleOrDefault();

                //return view model
                return View(mActionVM);
            }
        }

        //POST define edit action
        [HttpPost]
        public IActionResult Edit(MaintenanceActionViewModel obj)
        {
            //check for valid view model
            if(ModelState.IsValid)
            {
                using (MaintenanceActionDBContext db = new MaintenanceActionDBContext())
                {
                    //object for view model
                    MaintenanceAction ma = obj.NewMaintenanceAction;
                    //retrieve primary key/id from route data
                    ma.MaintenanceActionId = Guid.Parse(RouteData.Values["id"].ToString());
                    //update record status
                    db.Entry(ma).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

    }
}

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Views/MaintenanceAction/Edit.cshtml
@model SE406_Payne.Models.MaintenanceActionViewModel
@section list {
<h1>Maintenance Actions</h1>
}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            @using (Html.BeginForm("Edit", "MaintenanceAction", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceAction.MaintenanceActionId)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceAction.MaintenanceActionId,
                   new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceAction.MaintenanceActionId"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceAction.MaintenanceActionName)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceAction.MaintenanceActionName,
                   new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceAction.MaintenanceActionName"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-lg" />
                    <div class="btn btn-lg">
                        @Html.ActionLink("Back to Maintenance Actions", "Index")
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Lab_7/SE407_Payne_Lab7/SE406_Payne/src/SE406_Payne/Views/MaintenanceAction/Index.cshtml
@model SE406_Payne.Models.MaintenanceActionViewModel
@section list {
    <h1>Maintenance Actions</h1>
}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            @using (Html.BeginForm("Index", "MaintenanceAction", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceAction.MaintenanceActionId)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceAction.MaintenanceActionId,
                   new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceAction.MaintenanceActionId" 
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewMaintenanceAction.MaintenanceActionName)
                    @Html.TextBoxFor(Model => Model.NewMaintenanceAction.MaintenanceActionName,
                   new { @class = "form-control" })
                    <span asp-validation-for="@Model.NewMaintenanceAction.MaintenanceActionName"
                          class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-lg" />
                </div>
            }
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <h2>Maintenance Actions</h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>Maint Actions ID</th>
                        <th>Maint Actions Name</th>
                        <th> </th>
                    </tr>
                    @foreach (var MaintenanceAction in Model.MaintenanceActionList)
                    {
                        <tr>
                            <td>@MaintenanceAction.MaintenanceActionId</td>
                            <td>@MaintenanceAction.MaintenanceActionName</td>
                            <td><a asp-action="Edit" asp-route-id="@MaintenanceAction.MaintenanceActionId">Edit</a></td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>

</div>